### ISSUE TITLE
Skip the non-GPU tests on Buildkite

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaFolds/FoldsCUDA.jl#40]
Since the pool of JuliaGPU Buildkite runners is pretty small (right now we only have two GPU runners), we should make sure that we only run GPU tests on Buildkite.

We can detect if we are on Buildkite with:
```julia
haskey(ENV, "BUILDKITE")
```

If the `BUILDKITE` environment variable exists, we should skip the non-GPU tests.

cc: @tkf

**Comment by tkf** [comment]
Actually, "nongpu" tests here mean "tests that _can_ run without GPU but also have to be tested with GPU." I think there is a very small set of test that does not have to be run on GPU (namely test_aqua.jl). But I'll keep it in mind and try to pull out tests from GPU runners if possible.
